my_blog/article/urls.py
from django.urls import path
from . import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    # 首页
    path('', views.index, name='index'),
    # 文章列表
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 新建文章
    path('article-create/', views.article_create, name='article_create'),
    # 修改文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from os import environ


admin_path = environ.get('DJANGO_ADMIN_PATH')

urlpatterns = [
    path(admin_path, admin.site.urls),
    path('', include('article.urls', namespace='index')),
    # 新增代码，配置app的url
    # path('article/', include('article.urls', namespace='article')),
    # 用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]

my_blog/userprofile/urls.py
from django.urls import path
from . import views


app_name = 'userprofile'

urlpatterns = [
    # 用户页面
    path('profile/', views.profile, name='profile'),
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
]

my_blog/article/models.py
import markdown
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.utils.html import strip_tags
# Django-taggit
from taggit.managers import TaggableManager


# Create your models here.
class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    excerpt = models.CharField(max_length=200, blank=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    total_views = models.PositiveIntegerField(default=0)
    # 文章标签
    tags = TaggableManager(blank=True)

    class Meta:
        ordering = ('-created',)

    def save(self, *args, **kwargs):
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        self.excerpt = strip_tags(md.convert(self.body))[:100]
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.title

my_blog/userprofile/models.py
from django.db import models

# Create your models here.

my_blog/article/forms.py
from django import forms
from .models import ArticlePost


class ArticePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'excerpt', 'tags', 'body')

my_blog/userprofile/forms.py
# 引入表单类
from django import forms
# 引入 User 模型
from django.contrib.auth.models import User


# 登录表单，继承了 forms.Form 类
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

my_blog/article/views.py
import markdown
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render

from .forms import ArticePostForm
from .models import ArticlePost


# Create your views here.
def index(request):
    # return HttpResponse("Hello World!")
    search = request.GET.get('search')
    if search:
        article_list = ArticlePost.objects.filter(
            Q(title__icontains=search) | Q(body__icontains=search))
        paginator = Paginator(article_list, 10)
        page = request.GET.get('page')
        articles = paginator.get_page(page)
        context = {
            'articles': articles,
            'article_list_active': 'active',
            'search': search
        }
        return render(request, 'article/list.html', context)
    else:
        # 将 search 参数重置为空
        search = ''
        article_recent = ArticlePost.objects.all()[:4]
        context = {'articles': article_recent, 'index_active': 'active'}
        return render(request, 'index.html', context)


def article_list(request):
    # return HttpResponse("Hello World!")
    search = request.GET.get('search')
    tag = request.GET.get('tag')

    # 初始化查询集
    article_list = ArticlePost.objects.all()

    if search:
        article_list = ArticlePost.objects.filter(
            Q(title__icontains=search) | Q(body__icontains=search))
    else:
        # 将 search 参数重置为空
        search = ''
        article_list = ArticlePost.objects.all()

    # 标签查询集
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    paginator = Paginator(article_list, 10)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    context = {
        'articles': articles,
        'article_list_active': 'active',
        'search': search,
        'tag': tag,
    }
    return render(request, 'article/list.html', context)


def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    article.body = md.convert(article.body)
    # 浏览量 +1
    article.total_views += 1
    article.save(update_fields=['total_views'])

    context = {'article': article, 'toc': md.toc}
    return render(request, 'article/detail.html', context)


@login_required(login_url='/userprofile/login/')
def article_create(request):
    if request.method == "POST":
        article_post_form = ArticePostForm(data=request.POST)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=1)
            new_article.save()
            # 新增代码，保存 tags 的多对多关系
            article_post_form.save_m2m()
            return redirect("index:index")
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    else:
        article_post_form = ArticePostForm()
        context = {'article_post_form': article_post_form}
        return render(request, 'article/create.html', context)


@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    article = ArticlePost.objects.get(id=id)

    # 过滤非作者的用户
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")

    if request.method == "POST":
        article_post_form = ArticePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.excerpt = request.POST['excerpt']
            article.body = request.POST['body']
            article.tags.set(*request.POST.get('tags').split(','), clear=True)
            article.save()
            return redirect("index:article_detail", id=id)
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    else:
        article_post_form = ArticePostForm()
        context = {
            'article': article,
            'article_post_form': article_post_form,
            'tags': ','.join([x for x in article.tags.names()]),
        }
        return render(request, 'article/update.html', context)

my_blog/userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from .forms import UserLoginForm


# Create your views here.
def profile(request):
    return render(request, 'userprofile/profile.html')


def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法数据
            data = user_login_form.cleaned_data
            # 检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个 user 对象
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # 将用户数据保存在 session 中，即实现了登录动作
                login(request, user)
                return redirect("index:index")
            else:
                return HttpResponse("账号或密码输入有误。请重新输入~")
        else:
            return HttpResponse("账号或密码输入不合法")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = { 'form': user_login_form }
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


# 用户退出
def user_logout(request):
    logout(request)
    return redirect("index:index")

my_blog/templates/article/create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
BU's Blog：新建文章
{% endblock title %}

{% block content %}
<div class="container">
    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章摘要 -->
                <div class="form-group">
                    <label for="excerpt">文章摘要</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="excerpt" name="excerpt" rows="2"></textarea>
                </div>
                <!-- 文章标签 -->
                <div class="form-group">
                    <label for="tags">标签</label>
                    <input type="text" class="form-control col-3" id="tags" name="tags">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
    {% else %}
    <div class="container text-center">
        <br>
        <h3 class="heading">请先登录以创建文章</h3>
        <div class="intro">点击下面按钮以登录</div>
        <a class="nav-link" href="#">登录 &rarr;</a>
    </div>
    {% endif %}
</div>

{% endblock content %}

my_blog/templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
BU's Blog：{{ article.title }}
{% endblock title %}

{% block content %}
<article class="blog-post px-3 py-5 p-md-5">
    <div class="container">
        <header class="blog-post-header">
            <h2 class="title mb-2">{{ article.title }}</h2>
            <div class="meta mb-3">
                <span class="date">创建于 {{ article.created }}</span>
                <span class="date">更新于 {{ article.updated }}</span>
                <span class="time">{{ article.total_views }} 阅读</span>
                <span class="comment"><a href="#">4 comments</a></span>
                <span>
                    {% for tag in article.tags.all %}
                        <a href="{% url 'index:article_list' %}?tag={{ tag }}" class="badge badge-light">{{ tag }}</a>
                    {% endfor %}
                </span>
                {% if user.is_authenticated and user == article.author %}
                <span class="button"><a href="{% url 'index:article_update' article.id %}">修改文章</a></span>
                {% endif %}
            </div>            
        </header>
        <div class="blog-post-body">
            <p>{{ article.body|safe }}</p>
        </div>      
    </div>
</article>

{% endblock content %}

my_blog/templates/article/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
BU's Blog：首页
{% endblock title %}


{% block content %}
<section class="cta-section theme-bg-light py-5">
    <div class="container text-center">
        <form class="signup-form form-inline justify-content-center pt-3">
            <div class="form-group">
                <label class="sr-only" for="search">搜索</label>
                <input type="text" id="search" name="search" class="form-control mr-md-1" placeholder="输入搜索内容">
            </div>
            <button type="submit" class="btn btn-primary">搜索</button>
        </form>
    </div>
</section>
<section class="blog-list px-3 py-5 p-md-5">
    <div class="container">
        {% if search %}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
                <hr>        
            {% else %}
                <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
                <hr>
            {% endif %}
        {% endif %}
        {% for article in articles %}
        <div class="item mb-5">
            <div class="media">
                <!-- <img class="mr-3 img-fluid post-thumb d-none d-md-flex" src="{% static 'assets/images/blog/blog-post-thumb-1.jpg' %}" alt="image"> -->
                <div class="media-body">
                    <h3 class="title mb-1"><a href="{% url 'index:article_detail' article.id %}">{{ article.title }}</a></h3>
                    <div class="meta mb-1">
                        <span class="date">{{ article.created }}</span>
                        <span class="time">{{ article.total_views }} 阅读</span>
                        <span class="comment"><a href="#">8 comments</a></span>
                        <span>
                            {% for tag in article.tags.all %}
                                <a href="{% url 'index:article_list' %}?tag={{ tag }}" class="badge badge-light">{{ tag }}</a>
                            {% endfor %}
                        </span>
                    </div>
                    <div class="intro">{{ article.excerpt }}...</div>
                    <a class="more-link" href="{% url 'index:article_detail' article.id %}">继续阅读 &rarr;</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- 翻页导航 -->
    <nav class="blog-nav nav nav-justified my-5">
        {% if articles.has_previous %}
        <a class="nav-link-prev nav-item nav-link rounded-left"
            href="?page={{ articles.previous_page_number }}&search={{ search }}&tag={{ tag }}">Previous<i
                class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
        {% endif %}

        {% if articles.has_next %}
        <a class="nav-link-next nav-item nav-link rounded" href="?page={{ articles.next_page_number }}&search={{ search }}&tag={{ tag }}">Next<i
                class="arrow-next fas fa-long-arrow-alt-right"></i></a>
        {% endif %}
    </nav>
    
    <!-- 页码 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                {% if articles.has_previous %}
                    <a href="?page=1&search={{ search }}&tag={{ tag }}" class="font-paginator">
                        &laquo; 1
                    </a>
                    <span>...</span>
                {% endif %}
                
                {% if articles.paginator.num_pages > 1 %}
                    <span class="font-paginator" style="font-size: x-large">
                        {{ articles.number }}
                    </span>
                {% endif %}

                {% if articles.has_next %}
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&search={{ search }}&tag={{ tag }}" class="font-paginator">
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
    
</section>

{% endblock content %}

my_blog/templates/article/update.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
BU's Blog：修改文章
{% endblock title %}

{% block content %}
<div class="container">
    {% if user.is_authenticated and user == article.author %}
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <!-- 文章摘要 -->
                <div class="form-group">
                    <label for="excerpt">文章摘要</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="excerpt" name="excerpt" rows="2">{{ article.excerpt }}</textarea>
                </div>
                <!-- 文章标签 -->
                <div class="form-group">
                    <label for="tags">标签</label>
                    <input type="text" class="form-control col-3" id="tags" name="tags" value="{{ tags }}">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
    {% else %}
    <div class="container text-center">
        <br>
        <h3 class="heading">请先登录以修改文章</h3>
        <div class="intro">点击下面按钮以登录</div>
        <a class="nav-link" href="{% url 'userprofile:login' %}">登录 &rarr;</a>
    </div>
    {% endif %}
</div>

{% endblock content %}

my_blog/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn" class="h-100">

<head>
	<title>{% block title %}{% endblock %}</title>

	<!-- Meta -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Blog Template">
	<meta name="author" content="Xiaoying Riley at 3rd Wave Media">
	<link rel="shortcut icon" href="{% static 'favicon.ico' %}">

	<!-- FontAwesome JS-->
	<script defer src="https://cdn.bootcdn.net/ajax/libs/font-awesome/5.7.1/js/all.js"></script>

	<!-- Plugin CSS -->
	<link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/highlight.js/9.14.2/styles/monokai-sublime.min.css">

	<!-- Theme CSS -->
	<link id="theme-style" rel="stylesheet" href="{% static 'assets/css/theme-6.css' %}">

</head>

<body>

	<header class="header text-center">
		<h1 class="blog-name pt-lg-4 mb-0"><a href="{% url 'index:index' %}">BU's Blog</a></h1>
		<nav class="navbar navbar-expand-lg navbar-dark">

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
				aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div id="navigation" class="collapse navbar-collapse flex-column">
				<div class="profile-section pt-3 pt-lg-0">
					<img class="profile-image mb-3 rounded-circle mx-auto"
						src="{% static 'assets/images/profile.png' %}" alt="image">

					<div class="bio mb-3">
						大家好，欢迎访问 BU's Blog。<br>这是一个基于Django搭建的博客系统，比较简陋，纯属自娱自乐。
					</div>
					<!--//bio-->
					<ul class="social-list list-inline py-3 mx-auto">
						<li class="list-inline-item"><a href="https://weibo.com/crispding" target="_blank"><i class="fab fa-weibo fa-fw"></i></a></li>
						<li class="list-inline-item"><a href="https://github.com/crispding" target="_blank"><i class="fab fa-github-alt fa-fw"></i></a></li>
						<li class="list-inline-item"><a href="mailto:BU_Blog@outlook.com"><i class="far fa-envelope fa-fw"></i></i></a></li>
					</ul>
					<!--//social-list-->
					<hr>
				</div>
				<!--//profile-section-->
				<ul class="navbar-nav flex-column text-left">
					<li class="nav-item {{ index_active }}">
						<a class="nav-link" href="{% url 'index:index' %}"><i class="fas fa-home fa-fw mr-2"></i>博客首页 <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item {{ article_list_active }}">
						<a class="nav-link" href="{% url 'index:article_list' %}"><i class="fas fa-bookmark fa-fw mr-2"></i>文章列表</a>
					</li>
					<li class="nav-item">
						{% if user.is_authenticated %}
							<a class="nav-link" href="{% url 'userprofile:profile' %}"><i class="fas fa-user fa-fw mr-2"></i>用户页面</a>
						{% else %}
							<a class="nav-link" href="{% url 'userprofile:login' %}"><i class="fas fa-sign-in-alt fa-fw mr-2"></i>用户登录</a>
						{% endif %}
					</li>
				</ul>
			</div>
		</nav>
	</header>

	<div class="main-wrapper">

		<div id="wrapper">
			{% block content %}{% endblock content %}
		</div>

		<footer class="footer text-center py-2 theme-bg-dark" id="footer">

			<!--/* This template is released under the Creative Commons Attribution 3.0 License. Please keep the attribution link below when using for your own project. Thank you for your support. :) If you'd like to use the template without the attribution, you can buy the commercial license via our website: themes.3rdwavemedia.com */-->
			<small class="copyright">Designed with <i class="fas fa-heart" style="color: #fb866a;"></i> by <a
					href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
			<small class="copyright"><a href="http://beian.miit.gov.cn/" target="_blank">浙ICP备2021007773号</a></small>
		</footer>

	</div>

	<!-- Javascript -->
	<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="{% static 'assets/plugins/popper.min.js' %}"></script>
	<script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.3.0/js/bootstrap.min.js"></script>

	<!-- Page Specific JS -->
	<script src="https://cdn.bootcdn.net/ajax/libs/highlight.js/9.14.2/highlight.min.js"></script>

	<!-- Custom JS -->
	<script src="{% static 'assets/js/blog.js' %}"></script>
	
	<style>
		#wrapper {
			min-height: calc(100vh - 45px);
		}

		#footer {
			height: 45px;
		}
	</style>

</body>

</html>

my_blog/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
BU's Blog：首页
{% endblock title %}


{% block content %}
<section class="cta-section theme-bg-light py-5">
    <div class="container text-center">
        <h1 class="heading">BU's Blog</h1>
        <div class="intro">白昼朗朗，黑夜茫茫，魑魅魍魉，无所遁藏。恶徒奸党，惧吾神光，绿灯长明，万世光芒！</div>
        <form class="signup-form form-inline justify-content-center pt-3">
            <div class="form-group">
                <label class="sr-only" for="search">搜索</label>
                <input type="text" id="search" name="search" class="form-control mr-md-1" placeholder="输入搜索内容">
            </div>
            <button type="submit" class="btn btn-primary">搜索</button>
        </form>
    </div>
</section>

<section class="blog-list px-3 py-5 p-md-5">
    <div class="col-md-6 px-3">
        <h2 class="display-8">最新文章</h2>
    </div>
    <div class="row mb-2">
        {% for article in articles %}
            <div class="col-md-6">
            <div class="row no-gutters rounded overflow-hidden flex-md-row mb-4 h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary">
                    {% for tag in article.tags.all %}
                        <a href="{% url 'index:article_list' %}?tag={{ tag }}" class="badge badge-secondary">{{ tag }}</a>
                    {% endfor %}
                </strong>
                <h3 class="mb-0">{{ article.title }}</h3>
                <div class="meta mb-1"><span class="date">{{ article.created }}</span><span class="time">{{ article.total_views }} 阅读</span></div>
                <p class="card-text mb-auto">{{ article.excerpt }}...</p>
                <a href="{% url 'index:article_detail' article.id %}" class="stretched-link">继续阅读 &rarr;</a>
                </div>
                <!-- <div class="col-auto d-none d-lg-block">
                <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        
                </div> -->
            </div>
            </div>
        {% endfor %}
      </div>
      <div class="col-md-6 px-3">
        <p class="lead mb-0"><a href="{% url 'index:article_list' %}" class="font-weight-bold">更多……</a></p>  
      </div>  
</section>

{% endblock content %}

my_blog/templates/userprofile/login.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
BU's Blog：登录
{% endblock title %}

{% block content %}
<section class="cta-section theme-bg-light py-5">
    <div class="container text-center">
        <h1 class="heading">BU's Blog</h1>
        <div class="intro">白昼朗朗，黑夜茫茫，魑魅魍魉，无所遁藏。恶徒奸党，惧吾神光，绿灯长明，万世光芒！</div>
    </div>
</section>
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <!-- 密码 -->
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

my_blog/templates/userprofile/profile.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
BU's Blog：用户页面
{% endblock title %}

{% block content %}
<section class="cta-section theme-bg-light py-5">
    <div class="container text-center">
        <h1 class="heading">BU's Blog</h1>
        <div class="intro">白昼朗朗，黑夜茫茫，魑魅魍魉，无所遁藏。恶徒奸党，惧吾神光，绿灯长明，万世光芒！</div>
    </div>
</section>
<div class="container">
    <div class="row">
        <div class="col-12">
            {% if user.is_authenticated %}
            <h4 class="title mb-2 text-center">{{ user.username }} 已登录</h4>
            <div class="nav-item">
                <a class="nav-link" href="{% url 'index:article_create' %}"><i class="fas fa-plus-square fa-fw mr-2"></i>新建文章</a>
            </div>
            <div class="nav-item">
                <a class="nav-link" href="{% url 'userprofile:logout' %}"><i class="fas fa-sign-out-alt fa-fw mr-2"></i>退出登录</a>
            </div>
            {% else %}
            <h4 class="title mb-2 text-center">用户未登录，点击下方按钮登录</h4>
            <div class="nav-item">
                <a class="nav-link" href="{% url 'userprofile:login' %}"><i class="fas fa-sign-in-alt fa-fw mr-2"></i>登录</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}